#!/bin/sh
#
# Copyright © 2015-2021 the original authors.
#
# Gradle start up script for POSIX generated by "Gradle"
#

# Attempt to set APP_HOME
APP_HOME=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Default JVM options
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use JAVA_HOME if set, else just java
if [ -n "$JAVA_HOME" ] ; then
    JAVA_CMD=$JAVA_HOME/bin/java
else
    JAVA_CMD=java
fi

# Find and run gradle wrapper jar
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

exec "$JAVA_CMD" $DEFAULT_JVM_OPTS \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain "$@"
